# Generated by Django 3.0.3 on 2021-03-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0004_device_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='devmodel',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac',
        ),
    ]
