# Generated by Django 3.0.3 on 2021-03-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0006_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DeviceModel', to='provApp.DevModel'),
            preserve_default=False,
        ),
    ]
