# Generated by Django 3.0.3 on 2021-03-20 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0007_device_devmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cfg_last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
