# Generated by Django 3.0.3 on 2021-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0008_device_cfg_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default=123123123123123, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
