# Generated by Django 3.0.3 on 2021-03-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0009_device_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dss',
            name='device',
        ),
        migrations.AddField(
            model_name='dss',
            name='extension',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Extension', to='provApp.Extension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extension',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='provApp.Device'),
            preserve_default=False,
        ),
    ]
