# Generated by Django 3.0.3 on 2021-03-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0017_auto_20210320_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dss',
            name='extension',
        ),
        migrations.AddField(
            model_name='dss',
            name='device',
            field=models.ForeignKey(default=23123, on_delete=django.db.models.deletion.CASCADE, to='provApp.Device'),
            preserve_default=False,
        ),
    ]
