# Generated by Django 3.0.3 on 2021-03-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0018_auto_20210320_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='extension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Extension'),
        ),
    ]
