# Generated by Django 3.0.3 on 2021-03-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0023_auto_20210320_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cfg_last_update',
            field=models.DateTimeField(blank=True, verbose_name='Last config update'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.DevModel', verbose_name='Device Model'),
        ),
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=12, unique=True, verbose_name='MAC'),
        ),
    ]
