# Generated by Django 3.0.3 on 2021-03-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0024_auto_20210320_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
    ]
