# Generated by Django 3.0.3 on 2021-03-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0030_auto_20210321_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='device',
            field=models.ForeignKey(limit_choices_to={'device__devmodel__dss': 1}, on_delete=django.db.models.deletion.CASCADE, to='provApp.Device'),
        ),
    ]
