# Generated by Django 3.0.3 on 2021-03-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0031_auto_20210321_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devmodel',
            options={'verbose_name': 'Device model'},
        ),
        migrations.AlterModelOptions(
            name='devvendor',
            options={'verbose_name': 'Device vendor'},
        ),
        migrations.AlterModelOptions(
            name='dss',
            options={'verbose_name': 'DSS'},
        ),
        migrations.AlterField(
            model_name='device',
            name='cfg_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last config update'),
        ),
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='device',
            field=models.ForeignKey(limit_choices_to={'devmodel__dss': 1}, on_delete=django.db.models.deletion.CASCADE, to='provApp.Device', verbose_name='Device to connect DSS'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='dssType',
            field=models.TextField(choices=[('BLF - Busy Lamp Field', 'Blf'), ('SPD - Speed dial key', 'Spd')], default='BLF - Busy Lamp Field', max_length=45, verbose_name='DSS type'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='key',
            field=models.IntegerField(default=1, verbose_name='DSS key'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DSS label'),
        ),
        migrations.AlterField(
            model_name='dss',
            name='value',
            field=models.CharField(max_length=255, verbose_name='DSS value'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provApp.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.IntegerField(verbose_name='Extension name'),
        ),
    ]
