# Generated by Django 3.0.3 on 2021-03-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0032_auto_20210321_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.IntegerField(verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Extension name'),
        ),
    ]
