# Generated by Django 3.0.3 on 2021-03-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provApp', '0034_auto_20210323_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provApp.Extension'),
        ),
    ]
